site: Spindel
title: Spindel
greetings: Spindel 🕸️
description: >-
  A minimalist, quick search cybersecurity blog and cheatsheets
lang: en-US
timezone:  Asia/Singapore
repo: https://github.com/mvineza/spindel # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname

author:
  name: spindel
  bio: just a minimalist, personal blog
  userpicture:
  github: mvineza
  email: rell.vineza14@yahoo.com # email adress

# Font Settings
# googlewebfonts: family=SourceSans 3:wght@400;700
# googlewebfonts: Fira+Code:wght@400;500;700
# googlewebfonts: Ubuntu:wght@400;500;700

URL settings
Local development - remove urls
# url: ""
# baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
url: "https://mvineza.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/spindel" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


